apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeeye
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeeye
  template:
    metadata:
      labels:
        app: kubeeye
    spec:
      serviceAccountName: kubeeye
      containers:
        - name: kubeeye
          image: bchd.registry/kubeeye:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
